const js = require("@eslint/js");

module.exports = [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
      globals: {
        // Browser globals (for dashboard/assistant)
        window: "readonly",
        document: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        Response: "readonly",
        Request: "readonly",
        Headers: "readonly",
        navigator: "readonly",
        FormData: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        HTMLElement: "readonly",
        MutationObserver: "readonly",
        WebSocket: "readonly",
        EventSource: "readonly",
        AbortController: "readonly",
        crypto: "readonly",
        btoa: "readonly",
        atob: "readonly",
        self: "readonly",
        globalThis: "readonly",
        structuredClone: "readonly",
        queueMicrotask: "readonly",
        performance: "readonly",
        confirm: "readonly",
        alert: "readonly",
        prompt: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        IntersectionObserver: "readonly",
        ResizeObserver: "readonly",
        Image: "readonly",
        Audio: "readonly",
        location: "readonly",
        history: "readonly",
        matchMedia: "readonly",
        getComputedStyle: "readonly",
        requestIdleCallback: "readonly",
        // Node.js globals
        process: "readonly",
        console: "readonly",
        module: "readonly",
        require: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        exports: "writable",
        Buffer: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        setImmediate: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        // Jest globals
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        jest: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-console": "off",
      "no-useless-escape": "warn",
      "no-useless-catch": "warn",
      "no-prototype-builtins": "warn",
      "no-empty": "warn",
      "no-dupe-keys": "warn",
    },
  },
  // Frontend packages (dashboard + assistant widget run in the browser)
  {
    files: ["packages/dashboard/**/*.{js,jsx}", "packages/assistant/**/*.{js,jsx}"],
    rules: {
      "no-undef": "warn",
      "no-case-declarations": "warn",
      "no-redeclare": "warn",
    },
    linterOptions: {
      reportUnusedDisableDirectives: "off",
    },
  },
  {
    ignores: [
      "node_modules/",
      "dist/",
      ".next/",
      "out/",
      "coverage/",
      "site/",
      ".turbo/",
    ],
  },
];
