const express = require('express');
const userRouter = require('../modules/user/user.routes');
const organizationRouter = require('../modules/organization/organization.routes');
const organizationVersionControlRouter = require('../modules/organization_version_control/organization_version_control.routes');
const assistantDataRouter = require('../modules/assistant_data/assistant_data.routes');
const organizationMethodsRouter = require('../modules/organization_methods/organization_methods.routers');
const assistantAccessRouter = require('../modules/assistant_access/assistant_access.routes');
const organizationAssistantsRouter = require('../modules/organization_assistants/organization_assistants.routes');
const organizationConversationRouter = require('../modules/organization_conversation/organization_conversation.routes');
const emailRouter = require('./email.router');
const assistantInfoRouter = require('../modules/assistant_info/assistant_info.routes');
const conversationRouter = require('../modules/conversation/conversation.routes');
const interworkyAnalyticsRouter = require('../modules/interworky_analytics/interworky_analytics.routes');
const pluginStatusRouter = require('../modules/plugin_status/plugin_status.routes');
const performanceMonitoringRouter = require('../modules/performance_monitoring/performance_monitoring.routes');
const notificationsRouter = require('./notifications.router');
const openaiRouter = require('./openai.router');
const visitorJourneyRouter = require('../modules/visitor_journey/visitor_journey.routes');
const conversionConfigRouter = require('../modules/conversion_config/conversion_config.routes');
const organizationSecurityRouter = require('../modules/organization_security/organization_security.routes');
const personalizationRouter = require('../modules/personalization/personalization.routes');
const flowRouter = require('../modules/flow/flow.routes');
const flowActionRouter = require('../modules/flow_action/flow_action.routes');
const deviceTokenRouter = require('../modules/device_token/device_token.routes');
const googleCalendarRouter = require('./google_calendar.router');
const outlookCalendarRouter = require('./outlook_calendar.router');
const invitationRouter = require('../modules/invitation/invitation.routes');
const connectorRouter = require('../modules/connector/connector.routes');
const notificationPreferenceRouter = require('../modules/notification_preference/notification_preference.routes');
const indexRouter = express.Router();

indexRouter.use('/', userRouter);
indexRouter.use('/session-provider', openaiRouter);

indexRouter.use('/organizations', organizationRouter);
indexRouter.use('/organization-version-control', organizationVersionControlRouter);
indexRouter.use('/assistant_data', assistantDataRouter);
indexRouter.use('/organization-methods', organizationMethodsRouter);
indexRouter.use('/assistant_access', assistantAccessRouter);
indexRouter.use('/organization-assistants', organizationAssistantsRouter);
indexRouter.use('/organization-conversations', organizationConversationRouter);
indexRouter.use('/email', emailRouter);
indexRouter.use('/assistant-info', assistantInfoRouter);
indexRouter.use('/conversation', conversationRouter);
indexRouter.use('/notifications', notificationsRouter);
indexRouter.use('/interworky-analytics', interworkyAnalyticsRouter);
indexRouter.use('/plugin-status', pluginStatusRouter);
indexRouter.use('/performance-monitoring', performanceMonitoringRouter);
indexRouter.use('/visitor-journey', visitorJourneyRouter);
indexRouter.use('/conversion-config', conversionConfigRouter);
indexRouter.use('/organization-security', organizationSecurityRouter);
indexRouter.use('/personalization', personalizationRouter);
indexRouter.use('/flows', flowRouter);
indexRouter.use('/flow-action', flowActionRouter);
indexRouter.use('/device-tokens', deviceTokenRouter);
indexRouter.use('/google-calendar', googleCalendarRouter);
indexRouter.use('/outlook-calendar', outlookCalendarRouter);
indexRouter.use('/invitations', invitationRouter);
indexRouter.use('/connectors', connectorRouter);
indexRouter.use('/notification-preferences', notificationPreferenceRouter);

module.exports = indexRouter;
